name: Initialize Repository with Branches

on:
  push:
    branches:
      - main

jobs:
  setup-branches:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Create and push branches
      - name: Setup Git Branches
        run: |
          # Check the current branches
          echo "Current branches:"
          git branch -a

          # Create new branches
          echo "Creating branches..."
          git branch dev
          git branch qa
          git branch prod

          # Push branches to remote
          echo "Pushing branches to remote..."
          git push origin dev
          git push origin qa
          git push origin prod

          echo "Branches dev, qa, and prod have been created and pushed to remote."
